[project]
name = "codevia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "scrom-2511" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "requests>=2.34.2",
]

[project.scripts]
codevia = "codevia:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
